# Generated by Django 3.0.8 on 2020-08-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200131_0131'),
        ('todo', '0002_auto_20200813_2037'),
    ]

    operations = [
    ]
